max_retries = 2
retry_wait_time = 2
timeout = 20
insecure = false
accept = [200, 206, 301, 302, 303, 307, 308, 403, 429]
exclude = [
  "^http://localhost",
  "^https://localhost",
  "^http://127\\.0\\.0\\.1",
  "^https://127\\.0\\.0\\.1"
]
exclude_path = [
  "node_modules",
  "gemini-cli",
  "\\.agent",
  "\\.kiro"
]
